### PR TITLE
Upgrade to Spring 5.x and Spring Data 2.x

### PR DESCRIPTION
**Pull request by Hronom**
Now it able to work with Spring 5.x and Spring Data 2.x without workarounds.
Also upgraded other dependencies of the project.

The minimal version of Java also upgraded to 1.8. This is requirement of Spring 5.

This PR solves https://github.com/mongobee/mongobee/issues/75

### CODE REVIEW

**Comment by stefankatic** [comment]
+1.

**Comment by twoversionsofme** [comment]
This would be quite helpful. Any plans for this @lstolowski?

**Comment by dieppa** [comment]
Hello, I faced the same problem you are facing. I needed a change, made a PR but was never reviewed.
So I forked it and carried on independently. 

Please have a look at https://github.com/cloudyrock/mongock

It already provides improvements such as safe lock mechanism, multi-mode project, etc.
So you are welcome to provide your changes, I will review them within 1-2 days ;)
Thanks.

**Comment by abobwhite** [comment]
Thanks, @dieppa ! We are now looking into Mongock!

**Review by vladmm — APPROVED** [review]

**Pull request closed without merging**
