### PR TITLE
Remove the required need for Spring dependency.

### PR DESCRIPTION
**Pull request by derekbassett**
This small change removes the need to have spring in the dependency.  It can be safely excluded.

### CODE REVIEW

**Comment by lstolowski** [comment]
ChangeService:96 
`if (!element.isAnnotationPresent(Profile.class)) {`

Profile is a Spring's annotation so mongobee will still need Spring in dependencies. The goal it to remove Spring from dependencies and implement a possibility to attach it on demand (as a plugin, or a module)

Your change won't fix the problem. Am I wrong?

**Comment by derekbassett** [comment]
While the library still has a requirement to build with spring this allows a person to do this: 

`            <dependency>
                <groupId>com.github.mongobee</groupId>
                <artifactId>mongobee</artifactId>
                <version>${mongobee.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-context</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.springframework.data</groupId>
                        <artifactId>spring-data-mongodb</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>commons-logging</groupId>
                        <artifactId>commons-logging</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>`

Until such time as the library gets split into multiple modules this is a good work around.

**Comment by lstolowski** [comment]
should be removed when #34 is done

**Comment by derekbassett** [comment]
Any idea when the next dot release of mongobee's will happen?  Do you follow a tempo or are releases handled adhoc?

**Comment by lstolowski** [comment]
adhoc

**Comment by derekbassett** [comment]
Can I request a new release with all the current features?  It's been nine months since your last release and I would love to roll those changes into my software.

**Pull request merged**
