### PR TITLE
35 - process level lock to ensure only one instance of process is running

### PR DESCRIPTION
**Pull request by colsson11**
Hi there,

I've now implemented functionality for a global process lock as discussed. Please let me know what you think :)

Cheers,

Christian

### CODE REVIEW

**Comment by bgalek** [comment]
wanted to do similiar pull request today! +1 for U @colsson11

**Comment by mongobee** [comment]
Thanks Christian. I'm quite busy this time but I'll try to review all pull requests asap. Thanks again for your support :+1:

**Comment by colsson11** [comment]
Realized I forgot to make sure the lock is released, if there is an exception in the migration. Will add commit shortly.
- Christian

**Comment by colsson11** [comment]
Have pushed a commit to make sure the lock is always released. - C

**Pull request merged**
